#ifndef __REFRR_2010__
#define __REFRR_2010__

 
struct REFFR
{
	enum
	{
		FILE_FFR_UNJUDGE	= 0xffff,	//未判断

		FILE_NORMAL			= 0x0000,	//未知格式

		FILE_BND_EXECUTE	= 0x0100,	//可执行
		FILE_MEM			= FILE_BND_EXECUTE+0x01,
		FILE_BOOT			= FILE_BND_EXECUTE+0x02,
		FILE_COM			= FILE_BND_EXECUTE+0x03,
		FILE_MZ				= FILE_BND_EXECUTE+0x04,
		FILE_NE				= FILE_BND_EXECUTE+0x05,
		FILE_LE				= FILE_BND_EXECUTE+0x06,
		FILE_PE				= FILE_BND_EXECUTE+0x07,

		FILE_PE32P			= FILE_BND_EXECUTE+0x08,
		FILE_NET			= FILE_BND_EXECUTE+0x09,

		// 11 miss
		FILE_PEPACKER		= FILE_BND_EXECUTE+0x81,	// 加壳可执行

		// 11 miss
		FILE_PEResDropper	= FILE_BND_EXECUTE+0x82,	// 解PE资源(compound archive)
		// 11 miss
		FILE_PEPost			= FILE_BND_EXECUTE+0x83,	// PE后置查毒格式（处理资源无法回写的报毒显示同步）

		// 11 miss
		FILE_PEOnce			= FILE_BND_EXECUTE+0x84,	// PE最终扫描格式（查资源），08查未知、ScanEx家族扫描已在PE engine中自然处理

		// 11 miss
		FILE_PEOverlay		= FILE_BND_EXECUTE+0x85,	// PE文件Overlay处理(compound archive)
		// 11 miss
		FILE_PEScanOverlay	= FILE_BND_EXECUTE+0x86,	// Scan PE文件Overlay


		FILE_PESC			= FILE_BND_EXECUTE+0x87,


		FILE_BND_COMPRESS	= 0x0200,	//压缩包类型
		FILE_ZIP			= FILE_BND_COMPRESS+0x01,
		FILE_CAB			= FILE_BND_COMPRESS+0x02,
		FILE_ARJ			= FILE_BND_COMPRESS+0x03,
		FILE_RAR			= FILE_BND_COMPRESS+0x04,
		FILE_ARC			= FILE_BND_COMPRESS+0x05,
		FILE_ZOO			= FILE_BND_COMPRESS+0x06,
		FILE_LZH			= FILE_BND_COMPRESS+0x07,
		FILE_TAR			= FILE_BND_COMPRESS+0x08,
		FILE_GZIP			= FILE_BND_COMPRESS+0x09,
		FILE_UUE			= FILE_BND_COMPRESS+0x0A,
		FILE_ACE			= FILE_BND_COMPRESS+0x0B,
		FILE_BZ2			= FILE_BND_COMPRESS+0x0C,
		FILE_CHM			= FILE_BND_COMPRESS+0x0D,
		FILE_7Z				= FILE_BND_COMPRESS+0x0E,
		FILE_SIS			= FILE_BND_COMPRESS+0x0F,

		FILE_BND_SFX		= 0x0300,	//自解压可执行压缩包类型
		FILE_ZIPEXE			= FILE_BND_SFX+0x01,
		FILE_CABEXE			= FILE_BND_SFX+0x02,
		FILE_ARJEXE			= FILE_BND_SFX+0x03,
		FILE_RAREXE			= FILE_BND_SFX+0x04,
		FILE_ARCEXE			= FILE_BND_SFX+0x05,
		FILE_ZOOEXE			= FILE_BND_SFX+0x06,
		FILE_LZHEXE			= FILE_BND_SFX+0x07,
		FILE_ZIPNE			= FILE_BND_SFX+0x08,
		FILE_ZIPPE			= FILE_BND_SFX+0x09,
		FILE_ACEEXE			= FILE_BND_SFX+0x0A,
		FILE_NSISEXE		= FILE_BND_SFX+0x0B,
		FILE_INNOEXE		= FILE_BND_SFX+0x0C,
		FILE_7ZEXE			= FILE_BND_SFX+0x0D,
		FILE_CABSETEXE		= FILE_BND_SFX+0x0E, 
		FILE_SEAEXE			= FILE_BND_SFX+0x0F,
		FILE_WISEEXE		= FILE_BND_SFX+0x10,
		FILE_WISEADVEXE		= FILE_BND_SFX+0x11,
		FILE_AUTOIT			= FILE_BND_SFX+0x12,
		FILE_ELANG			= FILE_BND_SFX+0x13,
		FILE_GENTEE			= FILE_BND_SFX+0x14,
		FILE_PAQUET			= FILE_BND_SFX+0x15,
		FILE_INSTYLER		= FILE_BND_SFX+0x16,
		FILE_SFACTORY		= FILE_BND_SFX+0x17,
		FILE_QUICKBATCH		= FILE_BND_SFX+0x18,

		FILE_BND_OLE		= 0x0400,	//含宏
		FILE_DOC			= FILE_BND_OLE+0x1,
		FILE_DOT			= FILE_BND_OLE+0x2,
		FILE_XLS			= FILE_BND_OLE+0x3,
		FILE_PPT			= FILE_BND_OLE+0x4,
		FILE_MDB			= FILE_BND_OLE+0x5,

		FILE_WORD97			= FILE_BND_OLE+0x6,
		FILE_WORD6			= FILE_BND_OLE+0x7,
		FILE_EXCEL97		= FILE_BND_OLE+0x8,
		FILE_EXCEL6			= FILE_BND_OLE+0x9,

		FILE_MACRO			= FILE_BND_OLE+0xA,	//每个DOC文件默认含有宏格式
		FILE_PMACRO			= FILE_BND_OLE+0xB,	//临时使用的macro指针文件

		FILE_BND_MAILBOX	= 0x0500,	//邮箱类型
		FILE_OUTLOOKEX_V5	= FILE_BND_MAILBOX+0x01,
		FILE_OUTLOOKEX_V4	= FILE_BND_MAILBOX+0x02,
		FILE_FOXMAIL_V3		= FILE_BND_MAILBOX+0x03,
		FILE_NETSCAPE_V4	= FILE_BND_MAILBOX+0x04,

		FILE_BND_MAIL		= 0x0600,	//邮件类型
		FILE_EML			= FILE_BND_MAIL+0x01,
		FILE_NWS			= FILE_BND_MAIL+0x02,
		FILE_MHT			= FILE_BND_MAIL+0x03,
		FILE_MAILBODY		= FILE_BND_MAIL+0x04,
		FILE_MSG			= FILE_BND_MAIL+0x05,

		FILE_BND_SCRIPT		= 0x0700,	//含脚本
		FILE_HTM			= FILE_BND_SCRIPT+0x01,
		FILE_VBS			= FILE_BND_SCRIPT+0x02,
		FILE_VBE			= FILE_BND_SCRIPT+0x04,
		FILE_JS				= FILE_BND_SCRIPT+0x05,
		FILE_JSE			= FILE_BND_SCRIPT+0x06,
		FILE_CSS			= FILE_BND_SCRIPT+0x07,
		FILE_WSH			= FILE_BND_SCRIPT+0x08,
		FILE_SCT			= FILE_BND_SCRIPT+0x09,
		FILE_HTA			= FILE_BND_SCRIPT+0x0A,
		FILE_HTT			= FILE_BND_SCRIPT+0x0B,
		FILE_BAT			= FILE_BND_SCRIPT+0x0C,
		FILE_SCRIPT			= FILE_BND_SCRIPT+0x0D,	//是一统称
		FILE_ASP			= FILE_BND_SCRIPT+0x0E,
		FILE_PHP			= FILE_BND_SCRIPT+0x0F,
		FILE_PLG			= FILE_BND_SCRIPT+0x10,
		FILE_REG			= FILE_BND_SCRIPT+0x11,
		FILE_IRC			= FILE_BND_SCRIPT+0x12,	//[script]
		FILE_VBSENC			= FILE_BND_SCRIPT+0x13,
		FILE_JSENC			= FILE_BND_SCRIPT+0x14,
		FILE_PERL			= FILE_BND_SCRIPT+0x15,
		FILE_SHELL			= FILE_BND_SCRIPT+0x16,
		FILE_INF			= FILE_BND_SCRIPT+0x17,

		FILE_BND_FILE		= 0x0800,			//其他文件类型
		FILE_JPEG			= FILE_BND_FILE+0x01,
		FILE_SWF			= FILE_BND_FILE+0x02,
		FILE_INI			= FILE_BND_FILE+0x03,
		FILE_BASE64			= FILE_BND_FILE+0x04,
		FILE_UNICODE		= FILE_BND_FILE+0x05,
		
		FILE_PDF			= FILE_BND_FILE+0x06,
		FILE_PDF_COMP		= FILE_BND_FILE+0x07,

		FILE_TSKJOB			= FILE_BND_FILE+0x09,
		FILE_SWC			= FILE_BND_FILE+0x08,
		FILE_ASF			= FILE_BND_FILE+0x0A,
		FILE_TIFF			= FILE_BND_FILE+0x0B,
		FILE_QTMOV			= FILE_BND_FILE+0x0C,
		FILE_MP3			= FILE_BND_FILE+0x0D,
		FILE_LNK			= FILE_BND_FILE+0x0E,
		FILE_TTF			= FILE_BND_FILE+0x12,

		FILE_BND_OTHEROS	= 0x0900,	//其他操作系统的类型
		FILE_ELF			= FILE_BND_OTHEROS+0x01,

		//////////////////////////////////////////////////////////////////////////
		// Android
		FILE_BND_MOBILE		= 0x0A00,
		FILE_DEX			= FILE_BND_MOBILE+0x1,

		//////////////////////////////////////////////////////////////////////////
		

		FILE_BND_NOTSCAN	= 0x8000,	//不需要扫描
		FILE_NOTSCAN		= FILE_BND_NOTSCAN+0x01,
		FILE_TXT			= FILE_BND_NOTSCAN+0x02,
		FILE_RSBIN			= FILE_BND_NOTSCAN+0x03,
		FILE_CLASS			= FILE_BND_NOTSCAN+0x04,
		FILE_MAP			= FILE_BND_NOTSCAN+0x05,
		FILE_RTF			= FILE_BND_NOTSCAN+0x06,

		FILE_BMP			= FILE_BND_NOTSCAN+0x10,
		FILE_GIF			= FILE_BND_NOTSCAN+0x11,
		FILE_PIF			= FILE_BND_NOTSCAN+0x14,
		FILE_LOTUSPIC		= FILE_BND_NOTSCAN+0x15,
		FILE_PNG			= FILE_BND_NOTSCAN+0x16,

		FILE_ICO			= FILE_BND_NOTSCAN+0x21,
		FILE_CDR			= FILE_BND_NOTSCAN+0x22,
		FILE_MIDI			= FILE_BND_NOTSCAN+0x23,
		FILE_MPEG			= FILE_BND_NOTSCAN+0x24,

		FILE_HLP			= FILE_BND_NOTSCAN+0x26,
		FILE_IDS			= FILE_BND_NOTSCAN+0x27,
		FILE_WPG			= FILE_BND_NOTSCAN+0x28,
		FILE_LIM			= FILE_BND_NOTSCAN+0x29,
		FILE_CPT			= FILE_BND_NOTSCAN+0x2A,
		FILE_TEX			= FILE_BND_NOTSCAN+0x2B,
		FILE_CNT			= FILE_BND_NOTSCAN+0x2C,
		FILE_ISU			= FILE_BND_NOTSCAN+0x2D,
		FILE_WBM			= FILE_BND_NOTSCAN+0x2E,
		FILE_PNF			= FILE_BND_NOTSCAN+0x2F,
		FILE_APM			= FILE_BND_NOTSCAN+0x30,
		FILE_ANI			= FILE_BND_NOTSCAN+0x31,
		FILE_WMF			= FILE_BND_NOTSCAN+0x32,
		FILE_ICM			= FILE_BND_NOTSCAN+0x33,
		FILE_XML			= FILE_BND_NOTSCAN+0x34,
	};
};


class IREStream;

struct FFRINFO { DWORD pos, len; };

class IREFFR : public IUnknown
{
public:
	STDMETHOD(Open)(IREStream *pstm) = 0;
	STDMETHOD(Open)(BYTE *pbuf, DWORD cbSize) = 0;
	STDMETHOD(GetTypeCount)(OUT BYTE& rCount) = 0;
	STDMETHOD(GetTypes)(WORD *pTypes, IN OUT BYTE& rCount) = 0;
public:
	RE_DECLARE_IID;
};
RE_DEFINE_IID(IREFFR, "{040DB730-0C9D-4178-8ED3-51C990691CDE}",
0x40db730, 0xc9d, 0x4178, 0x8e, 0xd3, 0x51, 0xc9, 0x90, 0x69, 0x1c, 0xde);

//////////////////////////////////////////////////////////////////////////


// {C9BDBA1D-31EA-4790-8D62-0EC1CD9964C6}
DEFINE_GUID(CLSID_CREFFR, 
0xc9bdba1d, 0x31ea, 0x4790, 0x8d, 0x62, 0xe, 0xc1, 0xcd, 0x99, 0x64, 0xc6);


#endif	// #ifndef _RE_EXPORT_INTERFACE_FFR_H_

