#ifndef STRING_ENGLISH_H
#define STRING_ENGLISH_H

#define APP_NAME    "ESM Client"

#define STRING_OPERATE_MENU  "Operate"
#define STRING_OPERATE_QUICK_SCAN   "Quick scan"
#define STRING_OPERATE_ALL_SCAN     "All scan"
#define STRING_OPERATE_CUSTOM_SCAN  "Custom scan"
#define STRING_OPERATE_STOP_SCAN    "Stop scan"
#define STRING_OPERATE_EIXT         "Exit"

#define STRING_LOG_MENU     "Logs"
#define STRING_LOG_SCAN     "Scan logs"
#define STRING_LOG_VIRUS    "Virus logs"
#define STRING_LOG_BASE     "Base logs"
#define STRING_LOG_URL      "URL logs"

#define STRING_QUARANTINE   "Quarantine"

#define STRING_SETTING_MENU "Settings"
#define STRING_SETTING_SCAN "Scan settings"
#define STRING_SETTING_VIRUS    "Virus settings"
#define STRING_SETTING_WHITELIST "White list"
#define STRING_SETTING_PROCESSBL "Proc. list"
#define STRING_SETTING_FOLDERL 		"File list"
#define STRING_SETTING_BLACKLIST "URL block"
#define STRING_SETTING_DEFENCE   "DefenCenter"
#define STRING_SETTING_ADMIN    "Admin passwd"
#define STRING_SETTING_UPGRADE  "Upgrade settings"

#define STRING_ABOUT_MENU   "About"
#define STRING_ABOUT_UPGRADE    "Upgrade offline"
#define STRING_ABOUT_ABOUT      "About app."

#define STRING_PROMPT   "Prompt"
#define STRING_EXIT_PROM    "Exit the applicaton?"

#define STRING_BUTTON_YES   "YES"
#define STRING_BUTTON_NO    "NO"

#define STRING_SETTING_FILE_TYPE    "FileType"
#define STRING_SCAN_ALL_FILE        "All file"
#define STRING_SCAN_PRG_DOC         "Only execute and doc"
#define STRING_SCAN_ENGINE          "Scan Engine"
#define STRING_SCAN_POPULATE        "Scan populate virus"
#define STRING_SCAN_AI              "Use the AI scan"
#define STRING_SCAN_ZIP             "Scan compress file"
#define STRING_VIRUS_DEAL_TYPE      "Find virus"
#define STRING_VIRUS_AUTO_DEAL      "Auto"
#define STRING_VIRUS_MANUAL_DEAL     "Manually"
#define STRING_VIRUS_IGNORE         "Ignore"
#define STRING_CLEAN_FAILED         "Clean failed"
#define STRING_CLEAN_DELETE         "Delete"
#define STRING_CLEAN_IGNORE         "Ignore"

#define STRING_VIRUS_BACKUP         "Backup file"
#define STRING_VIRUS_BACKUP_FILE    "Backup virus file"
#define STRING_VIRUS_NO_BACKUP     "Not backup"
#define STRING_VIRUS_LARGE_FILE     "Large file"
#define STRING_QUERY_ME             "Query me"
#define STRING_DELTE_FILE           "Delete file"
#define STRING_VIRUS_SPACE_LESS     "Space less"
#define STRING_VIRUS_OVERRIDE_OLD   "Auto override old file"
#define STRING_VIRUS_SPACE_INCREAM  "Space auto incream"
#define STRING_BACKUP_FAILED        "Backup failed"

#define STRING_SCHEDULE_QUICK_SET   "Time quick"
#define STRING_SCHEDULE_FULL_SET    "Time full"
#define STRING_SCHEDULE_TIME        "scan time"
#define STRING_SCHEDULE_TYPE        "scan type"
#define STRING_SCHEDULE_STARTUP     "Power on"
#define STRING_SCHEDULE_DAYS        "every day"
#define STRING_SCHEDULE_WEEKS       "every week"
#define STRING_SCHEDULE_MONTHS      "every month"

#define STRING_OLD_PASSWORD         "Old password"
#define STRING_NEW_PASSWORD         "New password"
#define STRING_CONFIRM_PASSWORD     "Confirm password"

#define STRING_UPDATE_MODE          "Update mode"
#define STRING_UPDATE_MODE_MANUAL   "Manually"
#define STRING_UPDATE_MODE_DAYS     "Time in days"
#define STRING_UDPATE_MODE_WEEKS    "Day in weeds"
#define STRING_UPDATE_MODE_INTERVAL "Every time in..."
#define STRING_DELAY_START          "Delay start"
#define STRING_DISABLE              "Disable"
#define STRING_AUTO                 "Automatic"
#define STRING_ON_TIME              "Random in time"
#define STRING_UPDATE_CONTENT       "Update content"
#define STRING_UPDATE_ALL           "Update all"
#define STRING_UPDATE_VIRUSDB       "Virus db"
#define STRING_PROXY_SET            "Proxy set"
#define STRING_CONNECT_DIRECT       "Direct connect"
#define STRING_CONNECT_WITH_BROWERS "Use browser sett."
#define STRING_CONNECT_WITH_PROXY   "Use proxy"
#define STRING_UPDATE_SOURCE        "Upgrade source"
#define STRING_OFFICAL              "Offical"
#define STRING_OTHER                "Other"

#define STRING_APP_TITLE            "Rising ESM client"
#define STRING_VERSION              "Version"
#define STRING_VIRUS                "Virus version"
#define STRING_UPDATE_TIME          "Update time"
#define STRING_UPDATE_VIRUS_TIME    "Virus time"
#define STRING_LICENSE              "Copy right reserved by Rising Co."

#define STRING_CLOSE_DLG_PROMPT     "Press any key to close window..."

#define STRING_LIST_ID              "No."
#define STRING_LIST_TIME            "Time"
#define STRING_LIST_SOURCE          "Source"
#define STRING_LIST_STATUS          "Status"
#define STRING_LIST_COUNT           "Scan"
#define STRING_LIST_VIRUS           "Virus"
#define STRING_LIST_DEAL            "Deal"
#define STRING_LIST_PATH            "Path"
#define STRING_LIST_VNAME           "Name"
#define STRING_LIST_VTYPE           "Type"
#define STRING_LIST_BLONE           "Belong"
#define STRING_LIST_LOG_TYPE        "Type"
#define STRING_LIST_LOG_ACTION      "Action"
#define STRING_LIST_LOG_SOURCE      "From"
#define STRING_LIST_LOG_RESULT      "Result"

#define STRING_ADD_WHITE_LIST       "Add white list"
#define STRING_ADD_BLACK_LIST       "Add URL block list"
#define STRING_ADD_BLACK_PROC_LIST  "Add Proc. block list"
#define STRING_ADD_BLACK_FILE_LIST  "Add Folder monitor"

#define STRING_ADD_WHITE_PROMPT     "Inpurt"

#define FOOTER_VERSION  "Version"
#define FOOTER_UPDATE_TIME  "Update time"

#define REMOTE_COMMAND_NAME "Remote"
#define USER_MANUALLY_NAME  "Manually"
#define SCHEDULE_SCAN_NAME  "Timing"

#define FULL_SCAN_TYPE  "Full"
#define QUICK_SCAN_TYPE "Quick"
#define CUSTOM_SCAN_TYPE "Special"

#define VIRUS_DEAL_DEFAULT  "Dealed"
#define VIRUS_DEAL_IGNORE   "Ignore"
#define VIRUS_DEAL_CLEAN    "Cleaned"
#define VIRUS_DEAL_REMOVE   "Deleted"

#define SCAN_PROGRESS_NAME  "Progress"
#define SCAN_FINISH_PROMPT  "Scan finished"
#define SCAN_PREPARE_PROMPT "Scan starting"
#define SCAN_ERROR_PROMPT   "Scan error, try later"

#define INPUT_SCHEDULE_PARAMS   "Input time params"

#define STIRNG_SET_OPEN "On"
#define STRING_SET_CLOSE "Off"

#define STRING_PROCESS_DEFENCE_SET  "Proc. defen"
#define STRING_FILE_DEFENCE_SET     "File monitor"
#define STRING_PLUGIN_DEFENCE_SET   "Plugin monitor"
#define STRING_BROWSER_DEFENCE_SET  "Browser block"
#define STRING_NETFILTER_DEFENCE_SET "Net filter"

#endif // STRING_ENGLISH_H
