#ifndef __H_COMMON_H
#define __H_COMMON_H

//#define APP_SCREEN_WIDTH    920
//#define APP_SCREEN_HEIGHT   580
#define APP_SCREEN_WIDTH    880
#define APP_SCREEN_HEIGHT   570


//#define APP_HEADER_HEIGHT   195
#define APP_HEADER_HEIGHT   187
//#define APP_BODY_HEIGHT     425
#define APP_BODY_HEIGHT     393

//#define APP_TOP_BODY_HEIGHT 220
#define APP_TOP_BODY_HEIGHT 200
//#define APP_MID_BODY_HTIGHT 165
#define APP_MID_BODY_HTIGHT 152
#define APP_BOT_BODY_HEIGHT 40

#define APP_SCAN_TOP_BODY_HEIGHT    80
#define APP_SCAN_MID_BODY_HEIGHT    305

#define APP_EDGE_WIDTH      10
#define APP_TITLE_HEIGHT    50

#define LOGO_LEFT_MARGIN    30

#define DIR_SELECT_DIALOG_WODTH     320
#define DIR_SELECT_DIALOG_HEIGHT    380

#define APP_DEFEND_CENTER_DIALOG_WIDTH  720
#define APP_DEFEND_CENTER_DIALOG_HEIGHT 515//620
#define APP_DEFEND_CENTER_DIALOG_TITLE_HEIGHT   49


#define APP_IMG_LABLE_TEXT_FONT_SIZE    8   //for ImgTipsLable
#define APP_IMG_LABLE_TIPS_FONT_SIZE    6   //for ImgTipsLable

typedef enum APP_IMG_LABEL_TYPE{
    IMG_LABEL_TYPE_BASIC_ENGINE = 0,
    IMG_LABEL_TYPE_ADMIN_ENGINE,
    IMG_LABEL_TYPE_CLOUD_ENGINE,
    IMG_LABLE_TYPE_GENE_ENGINE
} ImgLabelType;

enum RAV_QT_VIRUS_SCAN_STATE{
    RAV_QT_VSCAN_STATE_NORMAL,
    RAV_QT_VSCAN_STATE_SCANING,
    RAV_QT_VSCAN_STATE_QUICK_SCANING,
    RAV_QT_VSCAN_STATE_CUSTOM_SCANING,
    RAV_QT_VSCAN_STATE_PAUSED,
    RAV_QT_VSCAN_STATE_READY_TO_STOP,
    RAV_QT_VSCAN_STATE_STOPPED,
    RAV_QT_VSCAN_STATE_READY
};

enum APP_DEFEND_WIDGET_TYPE{
    RAV_QT_DEFEND_TYPE_TROJAN = 0,
    RAV_QT_DEFEND_TYPE_FISHING,
    RAV_QT_DEFEND_TYPE_EVIL_DOWNLOAD,
    RAV_QT_DEFEND_TYPE_ANTI_HACKER,
    RAV_QT_DEFEND_TYPE_SITE_SCRIPTING,
    RAV_QT_DEFEND_TYPE_SEARCH_ENGINE,
    RAV_QT_DEFEND_TYPE_AD_FILTER,
    RAV_QT_DEFEND_TYPE_OUTER_ATTACK,
    RAV_QT_DEFEND_TYPE_ANTI_ARP,
    RAV_QT_DEFENT_TYPE_MORE
};

enum APP_DEFENDCENTER_ITEM_TYPE{
    RAV_QT_DEFENDCENTER_ITEM_TYPE_FILE = 0,
    RAV_QT_DEFENDCENTER_ITEM_TYPE_MAIL,
    RAV_QT_DEFENDCENTER_ITEM_TYPE_SHARE,
    RAV_QT_DEFENDCENTER_ITEM_TYPE_UDISK,
    RAV_QT_DEFENDCENTER_ITEM_TYPE_FEIKE = 6,
    RAV_QT_DEFENDCENTER_ITEM_TYPE_YUYUN,
    RAV_QT_DEFENDCENTER_ITEM_TYPE_WEIKE,
    RAV_QT_DEFENDCENTER_ITEM_TYPE_DLL
};

#ifndef u8
#define u8
#endif

#ifndef nullptr
#define nullptr 0
#endif

#ifndef Q_NULLPTR
#define Q_NULLPTR 0
#endif

#ifndef NULL
#define NULL 0
#endif

#define SECURITY_FREE(x) if(x) {delete x; x=NULL;}
#define SECURITY_CLOSE(x) if(x) {fclose(x); x=NULL;}
#define SECURITY_CHECK(x, y, z) if(x != y) return z;
#define ASSERT_ZERO(x, y) if(!x) return y;




#endif // COMMON_H
